spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: ae1113d438c0cf
    password: 801cfe565ed958
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

front-end-url: "http://localhost:4200/"