config.securite.active: false

spring:
  datasource:
    url: jdbc:h2:file:~/demodb;DB_CLOSE_DELAY=-1;
  jpa:
    hibernate:
      ddl-auto: update
blockchain:
  ethereum:
    inputUrl : https://speedy-nodes-nyc.moralis.io/b38206bb455593d951dbf660/polygon/mumbai
  chainID: 80001